### ISSUE TITLE
Two containers, one pod

### ISSUE THREAD

**Issue by FatmanUK** [athajaerel/tinykerb#1]
https://mohitgoyal.co/2021/04/23/spinning-up-and-managing-pods-with-multiple-containers-with-podman/

https://kubernetes.io/docs/tasks/access-application-cluster/communicate-containers-same-pod-shared-volume/

**Comment by athajaerel** [comment]
Is it actually three?

```
    kdc = kdc.k3s.lab:88
    admin_server = kad.k3s.lab:749
    kpasswd_server = kpw.k3s.lab:464
```
